# Generated by Django 3.1.7 on 2021-02-23 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('measure_unit', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('record_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.log')),
                ('sensor_pid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='models.sensor')),
            ],
        ),
    ]
