# Generated by Django 3.1.7 on 2021-07-13 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.BigIntegerField(null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('rows_number', models.IntegerField(default=0, null=True)),
                ('column_names', models.TextField(null=True)),
                ('classification_applied', models.BooleanField(default=False, null=True)),
                ('prediction_applied', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataTorque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('session', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('id_app', models.CharField(max_length=255, null=True)),
                ('time', models.BigIntegerField(null=True)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.DateTimeField(null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('id_app', models.CharField(max_length=255, null=True)),
                ('dataset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='models.dataset')),
            ],
            options={
                'unique_together': {('email', 'session')},
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('vehicle', models.CharField(max_length=255, null=True)),
                ('weight', models.FloatField(null=True)),
                ('fuel_type', models.CharField(max_length=50, null=True)),
                ('fuel_cost', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=255, unique=True)),
                ('user_full_name', models.CharField(max_length=255, null=True)),
                ('user_short_name', models.CharField(max_length=255, null=True)),
                ('ai4drive_name', models.CharField(max_length=255, null=True)),
                ('user_unit', models.CharField(max_length=50, null=True)),
                ('default_unit', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrackLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(null=True)),
                ('log', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='models.log')),
                ('track', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='models.track')),
            ],
        ),
        migrations.AddField(
            model_name='track',
            name='logs',
            field=models.ManyToManyField(through='models.TrackLog', to='models.Log'),
        ),
        migrations.CreateModel(
            name='SVM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('two_first_components_plot', models.TextField(null=True)),
                ('dataset', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='models.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, null=True)),
                ('time', models.DateTimeField(null=True)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.log')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_curve_plot', models.TextField(null=True)),
                ('prediction_plot', models.TextField(null=True)),
                ('time', models.DateTimeField(null=True)),
                ('rmse', models.FloatField(null=True)),
                ('feature', models.TextField(null=True)),
                ('epochs', models.IntegerField(default=0, null=True)),
                ('prediction_features_type', models.TextField(null=True)),
                ('principal_components_number', models.IntegerField(default=0, null=True)),
                ('dataset', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='models.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='KMeans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('two_first_components_plot', models.TextField(null=True)),
                ('explained_variance_ratio', models.TextField(null=True)),
                ('components_and_features_plot', models.TextField(null=True)),
                ('wcss_plot', models.TextField(null=True)),
                ('acumulative_explained_variance_ratio_plot', models.TextField(null=True)),
                ('cluster_list', models.TextField(null=True)),
                ('more_important_features', models.TextField(null=True)),
                ('dataset', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='models.dataset')),
            ],
        ),
    ]
