# Generated by Django 3.1.7 on 2021-03-03 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='log',
            unique_together=set(),
        ),
    ]
