# Generated by Django 3.1.7 on 2021-07-12 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tracklog',
            unique_together=set(),
        ),
    ]
