# Generated by Django 3.1.7 on 2021-02-23 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KMeans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('two_first_components_plot', models.TextField()),
                ('explained_variance_ratio', models.TextField()),
                ('components_and_features_plot', models.TextField()),
                ('wcss_plot', models.TextField()),
                ('acumulative_explained_variance_ratio_plot', models.TextField()),
                ('cluster_list', models.TextField()),
                ('more_important_features', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_curve_plot', models.TextField()),
                ('prediction_plot', models.TextField()),
                ('time', models.IntegerField()),
                ('rmse', models.FloatField()),
                ('feature', models.TextField()),
                ('epochs', models.IntegerField()),
                ('prediction_features_type', models.TextField()),
                ('principal_components_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SVM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('two_first_components_plot', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='sensor',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='measure_unit',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='pid',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.BigIntegerField()),
                ('name', models.TextField()),
                ('rows_number', models.IntegerField(default=0)),
                ('column_names', models.TextField()),
                ('classification_applied', models.BooleanField(default=False)),
                ('prediction_applied', models.BooleanField(default=False)),
                ('kmeans_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='models.kmeans')),
                ('log_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.log')),
                ('prediction_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='models.prediction')),
                ('svm_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='models.svm')),
            ],
        ),
    ]
