# Generated by Django 3.1.7 on 2021-02-23 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_auto_20210223_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='log_id',
        ),
        migrations.AddField(
            model_name='log',
            name='dataset_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='models.dataset'),
            preserve_default=False,
        ),
    ]
