# Generated by Django 3.1.7 on 2021-02-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_datatorque'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatorque',
            name='session',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
