# Generated by Django 3.1.7 on 2021-07-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_auto_20210715_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='value',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
