# Generated by Django 3.1.7 on 2021-03-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_auto_20210303_0921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('vehicle', models.CharField(max_length=255, null=True)),
                ('weight', models.FloatField(null=True)),
                ('fuel_type', models.CharField(max_length=50, null=True)),
                ('fuel_cost', models.FloatField(null=True)),
            ],
        ),
    ]
