# Generated by Django 3.1.7 on 2021-03-10 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_perfil'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Perfil',
            new_name='Profile',
        ),
    ]
