# Generated by Django 3.1.7 on 2021-02-23 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_auto_20210223_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='sensor_pid',
        ),
        migrations.AddField(
            model_name='sensor',
            name='record_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='models.record'),
            preserve_default=False,
        ),
    ]
