# Generated by Django 3.1.7 on 2021-02-23 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_auto_20210223_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='record_id',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='record_id',
        ),
        migrations.AddField(
            model_name='log',
            name='record_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='models.record'),
        ),
        migrations.AddField(
            model_name='record',
            name='sensor_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='models.sensor'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='kmeans_result',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='models.kmeans'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='prediction_result',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='models.prediction'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='svm_result',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='models.svm'),
        ),
        migrations.AlterField(
            model_name='log',
            name='dataset_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='models.dataset'),
        ),
    ]
