# Generated by Django 3.1.7 on 2021-03-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_log_id_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='time',
            field=models.BigIntegerField(null=True),
        ),
    ]
