# Generated by Django 3.1.7 on 2021-09-28 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_auto_20210928_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='models.log'),
        ),
        migrations.AlterField(
            model_name='record',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='models.sensor'),
        ),
    ]
