# Generated by Django 3.1.7 on 2021-03-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_record_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
