# Generated by Django 3.1.7 on 2021-02-23 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_auto_20210223_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='dataset_id',
            new_name='dataset',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='log_id',
            new_name='log',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='sensor_id',
            new_name='sensor',
        ),
    ]
