# Generated by Django 3.1.7 on 2021-10-08 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0008_auto_20210928_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='value',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
