# Generated by Django 3.1.7 on 2021-02-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0008_auto_20210223_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='pid',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
