# Generated by Django 3.1.7 on 2021-03-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0008_auto_20210310_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
