# Generated by Django 3.1.7 on 2021-02-23 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0009_auto_20210223_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='sensor',
        ),
        migrations.AddField(
            model_name='sensor',
            name='record',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='models.record'),
        ),
    ]
