# Generated by Django 3.1.7 on 2021-03-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0009_auto_20210311_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatorque',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='datatorque',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
