# Generated by Django 3.1.7 on 2021-02-23 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0010_auto_20210223_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='record',
        ),
        migrations.AddField(
            model_name='record',
            name='sensor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='models.sensor'),
        ),
    ]
