# Generated by Django 3.1.7 on 2021-11-11 14:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0010_auto_20211111_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='date',
        ),
        migrations.AddField(
            model_name='dataset',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataset',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
