# Generated by Django 3.1.7 on 2021-03-11 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0010_auto_20210311_1226'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='log',
            unique_together={('session', 'id_app')},
        ),
    ]
