# Generated by Django 3.1.7 on 2021-03-11 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0011_auto_20210311_1456'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='log',
            unique_together={('id_app', 'session')},
        ),
    ]
