# Generated by Django 3.1.7 on 2021-02-23 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0012_auto_20210223_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='kmeans_result',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='models.kmeans'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='prediction_result',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='models.prediction'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='svm_result',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='models.svm'),
        ),
    ]
