# Generated by Django 3.1.7 on 2021-11-11 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0012_auto_20211111_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='log',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='models.log'),
        ),
        migrations.AlterField(
            model_name='record',
            name='sensor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='models.sensor'),
        ),
    ]
