# Generated by Django 3.1.7 on 2021-03-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0013_auto_20210317_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatorque',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='log',
            unique_together={('email', 'session')},
        ),
    ]
