# Generated by Django 3.1.7 on 2021-04-05 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0014_auto_20210323_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='ai4drive_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_number', models.CharField(max_length=255, null=True)),
                ('road', models.CharField(max_length=255, null=True)),
                ('neighbourhood', models.CharField(max_length=255, null=True)),
                ('borough', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=255, null=True)),
                ('county', models.CharField(max_length=255, null=True)),
                ('state', models.CharField(max_length=255, null=True)),
                ('postcode', models.CharField(max_length=255, null=True)),
                ('country', models.CharField(max_length=255, null=True)),
                ('country_code', models.CharField(max_length=255, null=True)),
                ('log', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='models.log')),
            ],
        ),
    ]
