# Generated by Django 3.1.7 on 2021-02-23 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0014_auto_20210223_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='column_names',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='date',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='kmeans_result',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='models.kmeans'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='prediction_result',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='models.prediction'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='rows_number',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='svm_result',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='models.svm'),
        ),
    ]
