# Generated by Django 3.1.7 on 2021-02-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0015_auto_20210223_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='classification_applied',
            field=models.IntegerField(default=0, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='prediction_applied',
            field=models.IntegerField(default=0, max_length=1, null=True),
        ),
    ]
