# Generated by Django 3.1.7 on 2021-04-05 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0015_auto_20210405_1427'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('road', 'city', 'postcode', 'country')},
        ),
    ]
