# Generated by Django 3.1.7 on 2021-11-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0015_auto_20211111_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='kmeans',
            name='result',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='type',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
