# Generated by Django 3.1.7 on 2021-04-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0016_auto_20210405_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='log',
        ),
        migrations.AddField(
            model_name='address',
            name='log',
            field=models.ManyToManyField(to='models.Log'),
        ),
    ]
