# Generated by Django 3.1.7 on 2021-04-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0017_auto_20210405_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='session',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='time',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
