# Generated by Django 3.1.7 on 2021-02-24 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0017_auto_20210223_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kmeans',
            name='acumulative_explained_variance_ratio_plot',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='kmeans',
            name='cluster_list',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='kmeans',
            name='components_and_features_plot',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='kmeans',
            name='explained_variance_ratio',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='kmeans',
            name='more_important_features',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='kmeans',
            name='two_first_components_plot',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='kmeans',
            name='wcss_plot',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='epochs',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='feature',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='learning_curve_plot',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='prediction_features_type',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='prediction_plot',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='principal_components_number',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='rmse',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='time',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='measure_unit',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='svm',
            name='two_first_components_plot',
            field=models.TextField(null=True),
        ),
    ]
