# Generated by Django 3.1.7 on 2021-11-16 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0017_remove_kmeans_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co2_mean', models.FloatField(null=True)),
                ('speed_moving_mean', models.FloatField(null=True)),
                ('distance', models.FloatField(null=True)),
                ('duration', models.FloatField(null=True)),
                ('total_fuel_used', models.FloatField(null=True)),
                ('total_count_stop', models.FloatField(null=True)),
                ('total_car_off', models.FloatField(null=True)),
                ('city', models.FloatField(null=True)),
                ('hgwy', models.FloatField(null=True)),
                ('idle', models.FloatField(null=True)),
                ('log', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='models.log')),
            ],
        ),
    ]
