# Generated by Django 3.1.7 on 2021-02-24 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0018_auto_20210224_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='kmeans_result',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='models.kmeans'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='prediction_result',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='models.prediction'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='svm_result',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='models.svm'),
        ),
    ]
