# Generated by Django 3.1.7 on 2021-02-24 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0019_auto_20210224_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='kmeans_result',
            field=models.OneToOneField(blank=True, db_column='kmeans_result', null=True, on_delete=django.db.models.deletion.SET_NULL, to='models.kmeans'),
        ),
    ]
