# Generated by Django 3.1.7 on 2021-04-08 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0020_auto_20210408_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='session',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
